// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';

// Elements

export const USER_ROLE_FETCH_SUCCEEDED = 'USER_ROLE_FETCH_SUCCEEDED';
export const USERS_FETCH_SUCCEEDED = 'USERS_FETCH_SUCCEEDED';
export const VENDORS_FETCH_SUCCEEDED = 'VENDORS_FETCH_SUCCEEDED';
export const CUSTOMERS_FETCH_SUCCEEDED = 'CUSTOMERS_FETCH_SUCCEEDED';
export const STOCKS_FETCH_SUCCEEDED = 'STOCKS_FETCH_SUCCEEDED';
export const UTILIZATIONS_FETCH_SUCCEEDED = 'UTILIZATIONS_FETCH_SUCCEEDED';
export const PURCHASES_FETCH_SUCCEEDED = 'PURCHASES_FETCH_SUCCEEDED';
export const EXPENSES_FETCH_SUCCEEDED = 'EXPENSES_FETCH_SUCCEEDED';
export const INCOME_FETCH_SUCCEEDED = 'INCOME_FETCH_SUCCEEDED';
export const ORDERS_FETCH_SUCCEEDED = 'ORDERS_FETCH_SUCCEEDED';
export const EMPLOYEES_FETCH_SUCCEEDED = 'EMPLOYEES_FETCH_SUCCEEDED';

// App

export const NOTIFICATIONS_FETCH_SUCCEEDED = 'NOTIFICATIONS_FETCH_SUCCEEDED';
export const USER_LOGIN_SUCCEEDED = 'USER_LOGIN_SUCCEEDED';
export const SET_LOGGED_USERROLE = 'SET_LOGGED_USERROLE';
export const UTILIZATIONS_STATS_FETCH_SUCCEEDED = 'UTILIZATIONS_STATS_FETCH_SUCCEEDED';
